### ISSUE TITLE
igo/parser panics on empty string input.

### ISSUE THREAD

**Issue by dmitshur** [DAddYE/igo#1]
The standard parser does not panic with same input. It returns an error.

``` Go
package main

import (
    igo_parser "github.com/daddye/igo/parser"
    igo_token "github.com/daddye/igo/token"

    "fmt"
)

func main() {
    fset := igo_token.NewFileSet()
    _, err := igo_parser.ParseFile(fset, "", "", igo_parser.ParseComments|igo_parser.AllErrors)
    // Above panics.
    fmt.Println(err)
}
```

``` Go
package main

import (
    "go/parser"
    "go/token"

    "fmt"
)

func main() {
    fset := token.NewFileSet()
    _, err := parser.ParseFile(fset, "", "", parser.ParseComments|parser.AllErrors)
    // No panic, but non-nil error.
    fmt.Println(err)
}
```

![image](https://f.cloud.github.com/assets/1924134/2432098/33fff88a-ad52-11e3-940a-3c2dbedfa958.png)

**Comment by DAddYE** [comment]
This is the expected behavior (for now) it is helping me in tracking down parsing issues. You can see it here: https://github.com/DAddYE/igo/blob/master/parser/parser.go#L383-L384

**Comment by dmitshur** [comment]
I see. In that case, I'll ignore them on my side and you can close this issue.

**Comment by DAddYE** [comment]
Fixed!
