### ISSUE TITLE
consider renaming the project to goffee

### ISSUE THREAD

**Issue by will** [DAddYE/igo#3]

**Comment by DAddYE** [comment]
Nope, coffee change the semantic of the target language (js) where igo just the formatting.

**Comment by will** [comment]
:)

**Comment by vendethiel** [comment]
No, we really don't change the semantics ;-)

**Comment by will** [comment]
Yeah, I know. I just thought I came up with a great pun name.

**Comment by vendethiel** [comment]
I mean coffee doesn't change JS semantics. But I'm not starting a war anyway !

**Comment by DAddYE** [comment]
@Nami-Doc yep, sorry I was too generic but just wanted to stop a flame
