### ISSUE TITLE
syntax suggestion - get rid of parenthesis

### ISSUE THREAD

**Issue by parf** [DAddYE/igo#7]
p.say "Hello Sir."
=>
p.say("Hello Sir.")

**Comment by vendethiel** [comment]
Please, no. That's a pretty messy syntax

**Comment by DAddYE** [comment]
I concur with @a3gis and @Nami-Doc

**Comment by hmaurer** [comment]
I concur with @Nami-Doc; we should leave parentheses in for clarity.
