### ISSUE TITLE
Short function declaration bug (BadDecl)

### ISSUE THREAD

**Issue by blaxill** [DAddYE/igo#9]
Using short function declaration seems to cause parsing error of next function.

```
package main

func hello(text string)
    fmt.Println(text)

func hello2(text string): fmt.Println(text)

func main()
    return
```

Gives 

```
package main

func hello(text string) {
    fmt.Println(text)
}
func hello2(text string)    { fmt.Println(text) }

BadDecl
```

Note `BadDecl` instead of main function definition.

**Comment by DAddYE** [comment]
Thanks for pointing me this. Fixed and also improved a lot how comments are showed.

See: http://igo.herokuapp.com
